<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Authors>Harry Cordewener</Authors>
    <PackageProjectUrl>https://github.com/HarryCordewener/ladybugdb-dotnet-client</PackageProjectUrl>
    <RepositoryUrl>https://github.com/HarryCordewener/ladybugdb-dotnet-client</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>
</Project>
